### ISSUE TITLE
could you help me out on a couple of things please

### ISSUE THREAD

**Issue by gitreapur** [shazChaudhry/elastic#20]
Hello,
I'm trying to deploy your cluster in the hope that I can learn more about this ELK.
I have some questions:
1- can you please explain this:
    alias git='docker run -it --rm --name git -v $PWD:/git -w /git indiehosters/git git'
2- I am unable to create this ( I did not install beats.):
     On the Kibana Management tab, configure an index pattern, Index name or pattern = filebeat-*
3- Edit "filebeat-docker-compose.yml" file. Change environment variables for Kibana and Elasticseaerch 
      hosts
     - Does this need the actual IP address?

Thanks

**Comment by shazChaudhry** [comment]
Sorry for the delayed response. I did not see this issue until now. Also, please note that I have updated my stack to v6.5.0 which is the latest version at the time of writing this. README has also been updated and hopefully you will find it simpler to follow.

Q1 - Please see the updated README. The answer should be clear now
Q2 - You will need to follow "Deploy Beats" section in order to deploy beats. If beats are not shipping logs to Elasticsearch, you will not be able to create / see filebeat index in Kibana
Q3 - If you get my latest repo, you will no longer need to change the "filebeat-docker-compose.yml" file. The hostname or IPs of your Elasticsearch and Kibana instances are set as environment variables on the commandline (latest version of README should be easier to follow)

If you still need further help, please give us a shout

**Comment by gitreapur** [comment]
Thanks Shaz, I'll give this a test asap. I did review the changes and it looks really promising.
I wonder if you'll ever do a project for redis cluster on docker swarm. I'm having many issues scaling it out.
