### ISSUE TITLE
Elastisearch cluster fails when change data path

### ISSUE THREAD

**Issue by jabibenito** [shazChaudhry/elastic#35]
Hello,

When I launch stack with this volumen path works fine

```
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
```
If I change the volume path to another location.

```
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
```

Shows me this error and never creates the cluster.

`{"type": "server", "timestamp": "2020-05-28T07:35:05,570Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "DevOps", "node.name": "ig-dockerdev-01", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [node1] to bootstrap a cluster: have discovered [{ig-dockerdev-01}{yCtLfa_IS_OOL6gvDnMnsA}{f8BlMJRGQ7GJ7ChMnUZjMA}{10.0.15.145}{10.0.15.145:9300}{dimrt}{xpack.installed=true, transform.node=true}, {ig-dockerdev-03}{KoHiSiuITV2YmVGkEXxtIQ}{b95IUP-jRBuhyR-mvyetAQ}{10.0.15.143}{10.0.15.143:9300}{dimrt}{xpack.installed=true, transform.node=true}, {ig-dockerdev-02}{OVrgsX9NRp6OIh2Jo5FcQQ}{Ysl3vSx4SBWwT_Mq3U4Lkw}{10.0.15.144}{10.0.15.144:9300}{dimrt}{xpack.installed=true, transform.node=true}]; discovery will continue using [10.0.15.144:9300, 10.0.15.143:9300] from hosts providers and [{ig-dockerdev-01}{yCtLfa_IS_OOL6gvDnMnsA}{f8BlMJRGQ7GJ7ChMnUZjMA}{10.0.15.145}{10.0.15.145:9300}{dimrt}{xpack.installed=true, transform.node=true}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }`

**Comment by jabibenito** [comment]
This error was because I forgot change the node name. After change this, stack is running but elasticsearch does not respond in 9200 port. I need to change anything ese?

Could you share an example with volumes located in another location different to default location?

**Comment by shazChaudhry** [comment]
I am sorry I am not sure if I following.
1) Is the volume an issue? Is elasticsearch not starting because you are giving the volume a location?
2) Or is the port an issue? are you not able to send logs or metrics to elasticsearch?

**Comment by shazChaudhry** [comment]
`This error was because I forgot change the node name. After change this, stack is running but elasticsearch does not respond in 9200 port. I need to change anything ese?`
- Using the [Vagrantfile](https://github.com/shazChaudhry/docker-elastic/blob/master/Vagrantfile) provided in this repo, I have just deployed a new stack following the instructions in README. 
- And I am able to access elasticsearch at "http://node1:9200/". I did not modify anything.

`Could you share an example with volumes located in another location different to default location?`
- By default location, I am assuming you mean named volumes. For mounting your own host path, you could try short syntax of [volumes](https://docs.docker.com/compose/compose-file/#volumes)
- please also, see [volumes-for-services-swarms-and-stack-files](https://docs.docker.com/compose/compose-file/#volumes-for-services-swarms-and-stack-files) for why named volumes should be used

I hope this answers your questions. Please give us a shout if you have further questions regarding this repository
